# Generated by Django 5.1.6 on 2025-02-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
